language: php
php:
  - '5.6'

services:
  - mysql

before_install: mysql -u root --password="" < test.sql

before_script: composer install

script: phpunit integration_test.php

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true
