language: php
php:
  - '5.6'

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root

services:
  - mysql

before_install: composer install

script: phpunit integration_test.php

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true